package:
  name: spacepy
  version: "0.1.6"

source:
  fn: spacepy-0.1.6.tar.gz
  url: https://pypi.python.org/packages/f7/10/4a9a43014d25c1ce08aad136da2515eb120a26105dec5e8f42b5986c22a3/spacepy-0.1.6.tar.gz
  md5: 1272ec6537ca45b6e4b8ea3f8c2cf8a1

build:
  number: 0
  features:
    - vc9      [win and py27]
    - vc10     [win and py34]
    - vc14     [win and py35]

requirements:
  build:
    - python
    - numpy >= 1.10
    - gcc      [not win]
    - mingwpy  [win32]
    - m2w64-gcc-fortran  [win64]
    - toolchain

  run:
    - python
    - numpy >= 1.10
    - scipy
    - matplotlib
    - python-dateutil
    - h5py
    - libgfortran   [not win]
    - libgcc        [not win]
    - m2w64-gcc-libgfortran [win64]

test:
  imports:
    - spacepy
    - spacepy.irbempy
    - spacepy.plot
    - spacepy.pybats
    - spacepy.pycdf
    - spacepy.toolbox

about:
  home: http://spacepy.lanl.gov
  license: Python Software Foundation License
  summary: 'SpacePy: Tools for Space Science Applications'

extra:
  recipe-maintainers:
    - AlexS12
