package:
  name: spacepy
  version: "0.1.6"

source:
  fn: spacepy-0.1.6.tar.gz
  url: https://pypi.python.org/packages/f7/10/4a9a43014d25c1ce08aad136da2515eb120a26105dec5e8f42b5986c22a3/spacepy-0.1.6.tar.gz
  md5: 1272ec6537ca45b6e4b8ea3f8c2cf8a1

build:
  number: 0

requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - python_dateutil
    - h5py

test:
  imports:
    - spacepy
    - spacepy.irbempy
    - spacepy.plot
    - spacepy.pybats
    - spacepy.pycdf
    - spacepy.toolbox

about:
  home: http://spacepy.lanl.gov
  license: Python Software Foundation License
  summary: 'SpacePy: Tools for Space Science Applications'

extra:
  recipe-maintainers:
    - AlexS12
